Fix crash caused due to decorators not having id attribute
This fixes the following error while running the package.

```
File "/home/thomas/.local/lib/python3.10/site-packages/deadcode/visitor/utils.py", line 61, in get_decorator_name
    parts.append(decorator.id)  # type: ignore
AttributeError: 'Lambda' object has no attribute 'id'
```
Fixes: #29